FROM test:5.0
MAINTAINER WuJian_Home
# RUN apt-get update
# RUN apt-get install python3-pip
#COPY requirements.txt /home/cch/Comman/
#RUN pip3 install --no-cache-dir -r /home/cch/Comman/requirements.txt
#COPY  ./Comman/ /home/cch/Comman/
# CMD ["home/cch/Comman/main.py"]
